[ubuntu]
edge-prod-01.dontddos.me ansible_port=47382
mail-prod-01.dontddos.me ansible_port=47382
docker-prod-01.local.dontddos.me
docker-prod-02.local.dontddos.me
dns-prod-01.local.dontddos.me

[vps]
edge-prod-01.dontddos.me ansible_port=47382
mail-prod-01.dontddos.me ansible_port=47382

[docker]
edge-prod-01.dontddos.me ansible_port=47382
mail-prod-01.dontddos.me ansible_port=47382
docker-prod-01.local.dontddos.me
docker-prod-02.local.dontddos.me
dns-prod-01.local.dontddos.me