[vps]
edge-prod-01.dontddos.me
mail-prod-01.dontddos.me

[vps:vars]
ansible_port=47382

[docker_local]
docker-prod-01.local.dontddos.me
docker-prod-02.local.dontddos.me
docker-prod-03.local.dontddos.me
dns-prod-01.local.dontddos.me

[docker:children]
docker_local

[ubuntu_local:children]
docker_local

[ubuntu:children]
vps
ubuntu_local
