[ubuntu]
edge-prod-01.dontddos.me
mail-prod-01.dontddos.me
docker-prod-01.local.dontddos.me
dns-prod-01.local.dontddos.me

[vps]
edge-prod-01.dontddos.me
mail-prod-01.dontddos.me

[docker]
edge-prod-01.dontddos.me
mail-prod-01.dontddos.me
docker-prod-01.local.dontddos.me
dns-prod-01.local.dontddos.me