---
services:
  inkfra:
    image: ddosian/inkfra:latest
    volumes:
      - /opt/containers/inkfra/config:/config:ro
      - /opt/containers/inkfra/output:/output:rw
    networks:
      - newt
    restart: unless-stopped
networks:
  newt:
    external: true
